apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-sinlessgames
  namespace: networking
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: cloudflared-sinlessgames
    creationPolicy: Owner
  data:
    - secretKey: tunnel_id
      remoteRef:
        key: cloudflare/tunnel/sinlessgames
        property: tunnel_id
    - secretKey: tunnel_token
      remoteRef:
        key: cloudflare/tunnel/sinlessgames
        property: tunnel_token
    - secretKey: zone_id
      remoteRef:
        key: cloudflare/tunnel/sinlessgames
        property: zone_id
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-helix
  namespace: networking
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: cloudflared-helix
    creationPolicy: Owner
  data:
    - secretKey: tunnel_id
      remoteRef:
        key: cloudflare/tunnel/helix
        property: tunnel_id
    - secretKey: tunnel_token
      remoteRef:
        key: cloudflare/tunnel/helix
        property: tunnel_token
    - secretKey: zone_id
      remoteRef:
        key: cloudflare/tunnel/helix
        property: zone_id
