# Kubernetes/apps/prod/networking/cloudflared/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudflared
  namespace: networking
  labels:
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/component: service-account
    app.kubernetes.io/part-of: edge-access
    security.sinlessgames.io/rbac: none-required
automountServiceAccountToken: false