defaultSettings:
  defaultDataPath: /var/lib/longhorn
  defaultReplicaCount: 3
  backupTarget: s3://k8s-prod-longhorn@auto/
  backupTargetCredentialSecret: longhorn-backup-credentials
  createDefaultDiskLabeledNodes: false
  storageOverProvisioningPercentage: 300
  storageMinimalAvailablePercentage: 15
  replicaAutoBalance: best-effort
  taintToleration: nvidia.com/gpu=true:NoSchedule
preUpgradeChecker:
  jobEnabled: false
tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
longhornUI:
  replicas: 2
persistence:
  defaultClass: true
  defaultClassReplicaCount: 3
metrics:
  serviceMonitor:
    enabled: true
