defaultSettings:
  defaultDataPath: /var/lib/longhorn
  defaultReplicaCount: 3
  backupTarget: s3://k8s-prod-longhorn@auto/
  backupTargetCredentialSecret: longhorn-backup-credentials
  createDefaultDiskLabeledNodes: true
  storageOverProvisioningPercentage: 150
  storageMinimalAvailablePercentage: 15
  replicaAutoBalance: best-effort
longhornUI:
  replicas: 2
persistence:
  defaultClass: true
  defaultClassReplicaCount: 3
metrics:
  serviceMonitor:
    enabled: true
