service:
  type: LoadBalancer
  annotations:
    metallb.universe.tf/address-pool: prod-services
resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 1Gi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
