---
# KV v2 secrets engines
vault_kv_mounts:
  secrets:
    description: "Centralized secrets storage (KV v2)"
    options:
      version: "2"

# Non-KV secrets engines
vault_engine_mounts:
  transit:
    type: "transit"
    description: "Transit secrets engine"
  kubernetes-dev:
    type: "kubernetes"
    description: "Kubernetes secrets engine for development service account roles"
  kubernetes-staging:
    type: "kubernetes"
    description: "Kubernetes secrets engine for staging service account roles"
  kubernetes-prod:
    type: "kubernetes"
    description: "Kubernetes secrets engine for production service account roles"

# Transit secrets engine configuration
vault_transit_configs:
  transit:
    keys:
      - name: "default"
        type: "aes256-gcm96"
        exportable: false
