# Kubernetes/apps/prod/monitoring/config/externalsecret-grafana-admin.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana-admin
    app.kubernetes.io/component: admin-credentials
    app.kubernetes.io/part-of: grafana
    security.sinlessgames.io/secret-source: vault
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend

  target:
    name: grafana-admin
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          app.kubernetes.io/name: grafana-admin
          app.kubernetes.io/component: admin-credentials
          app.kubernetes.io/part-of: grafana
          security.sinlessgames.io/managed-by: external-secrets
      data:
        admin-user: admin
        grafana_admin_password: "{{ .grafanaAdminPassword }}"
        postgres_grafana_password: "{{ .postgresGrafanaPassword }}"
        discord_alert_webhook_url: "{{ .discordAlertWebhookUrl }}"

  data:
    - secretKey: grafanaAdminPassword
      remoteRef:
        key: kubernetes/production/integrations
        property: grafana_admin_password

    - secretKey: postgresGrafanaPassword
      remoteRef:
        key: kubernetes/production/integrations
        property: postgres_grafana_password

    - secretKey: discordAlertWebhookUrl
      remoteRef:
        key: kubernetes/production/integrations
        property: discord_alert_webhook_url