# Kubernetes/apps/prod/monitoring/config/externalsecret-observability.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: observability-object-storage
  namespace: monitoring
  labels:
    app.kubernetes.io/name: observability-object-storage
    app.kubernetes.io/component: object-storage-credentials
    app.kubernetes.io/part-of: monitoring
    security.sinlessgames.io/secret-source: vault
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend

  target:
    name: observability-object-storage
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: observability-object-storage
          app.kubernetes.io/component: object-storage-credentials
          app.kubernetes.io/part-of: monitoring
          security.sinlessgames.io/managed-by: external-secrets

  data:
    - secretKey: S3_ENDPOINT
      remoteRef:
        key: kubernetes/production/integrations
        property: garage_s3_endpoint_internal

    - secretKey: S3_REGION
      remoteRef:
        key: kubernetes/production/integrations
        property: s3_region

    - secretKey: S3_FORCE_PATH_STYLE
      remoteRef:
        key: kubernetes/production/integrations
        property: s3_force_path_style

    - secretKey: S3_INSECURE
      remoteRef:
        key: kubernetes/production/integrations
        property: s3_insecure