apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: grafana-admin
    template:
      data:
        admin-user: admin
        grafana_admin_password: "{{ `{{ .grafana_admin_password }}` }}"
  data:
    - secretKey: grafana_admin_password
      remoteRef:
        key: kubernetes/production/integrations
        property: grafana_admin_password
