apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alertmanager-kube-prometheus-stack.yaml
  - daemonset-cadvisor.yaml
  - deployment-otel-collector.yaml
  - destinationrule-observability.yaml
  - service-cadvisor.yaml
  - configmap-grafana-dashboard-observability.yaml
  - configmap-grafana-nsswitch.yaml
  - service-otel-collector.yaml
  - prometheus-kube-prometheus-stack.yaml
  - servicemonitor-cadvisor.yaml
  - servicemonitor-otel-collector.yaml
  - externalsecret-grafana-admin.yaml
  - externalsecret-loki-s3.yaml
  - externalsecret-mimir-s3.yaml
  - externalsecret-tempo-s3.yaml
  - externalsecret-pyroscope-s3.yaml
  - serviceentry-vault.yaml
  - virtualservice-observability.yaml
