---
- name: "Restart vault service"
  systemd:
    name: vault
    state: restarted
    daemon_reload: true
  listen: "restart vault"

- name: "Reload vault systemd daemon"
  systemd:
    daemon_reload: true
  listen: "reload vault systemd"

- name: "Restart haproxy service"
  systemd:
    name: haproxy
    state: restarted
  listen: "restart haproxy"

- name: "Restart keepalived service"
  systemd:
    name: keepalived
    state: restarted
  listen: "restart keepalived"

- name: "Enable and start vault service"
  systemd:
    name: vault
    state: started
    enabled: true
    daemon_reload: true
  listen: "start vault"
