
// ============================================================================
// Kubernetes Cluster Terraform Configuration - Generated by Ansible
// ============================================================================
// Source: Ansible/roles/kubernetes-deploy/tasks/main.yaml
// Template: Ansible/roles/kubernetes-deploy/templates/k8s-dev-cluster.tf.j2
// DO NOT EDIT MANUALLY - this file is overwritten during deployment
// ============================================================================

module "kubernetes_dev_master" {
  source = "./modules/proxmox-vm-cluster"

  # --------------------------------------------------------------------------
  # Cluster identity
  # --------------------------------------------------------------------------
  cluster_name = "k8s-dev"
  environment  = "dev"
  service_name = "kubernetes"
  node_role    = "master"

  # --------------------------------------------------------------------------
  # Node definitions
  # --------------------------------------------------------------------------
  nodes = [    {
      name        = "k8s-dev-master-01"
      vmid        = 300
      target_node = "pve-01"
      ip_address  = "10.10.20.11"
      hostname    = "k8s-dev-master-01"
      fqdn        = "k8s-dev-master-01.dev.k8s.sinlessgames.com"
      storage     = "vm_disks_01"
    }  ]

  # --------------------------------------------------------------------------
  # Proxmox configuration
  # --------------------------------------------------------------------------
  clone_template = "debian-13-template"
  storage        = "VM_Disks"

  # --------------------------------------------------------------------------
  # Resource allocation
  # --------------------------------------------------------------------------
  cpu_cores   = 4
  cpu_sockets = 1
  memory_mb   = 8192
  disk_size   = "100G"

  # --------------------------------------------------------------------------
  # Network configuration
  # --------------------------------------------------------------------------
  network_bridge = "vmbr1"
  vlan_id        = 20
  gateway        = "10.10.20.1"
  cidr_subnet    = "/24"
  nameservers    = "10.10.10.1 1.1.1.1"
  search_domain  = "dev.k8s.sinlessgames.com"

  # --------------------------------------------------------------------------
  # Metadata / access
  # --------------------------------------------------------------------------
  tags = [
    "kubernetes",
    "rke2",
    "master"
  ]

  ssh_keys     = var.kubernetes_ssh_keys
  default_user = "sinless777"
  cicustom_user_snippet_enabled = true

  # --------------------------------------------------------------------------
  # Lifecycle
  # --------------------------------------------------------------------------
  start_at_node_boot = true
  force_create       = true
  startup_order      = 10
}

module "kubernetes_dev_worker" {
  source = "./modules/proxmox-vm-cluster"

  # --------------------------------------------------------------------------
  # Cluster identity
  # --------------------------------------------------------------------------
  cluster_name = "k8s-dev"
  environment  = "dev"
  service_name = "kubernetes"
  node_role    = "worker"

  # --------------------------------------------------------------------------
  # Node definitions
  # --------------------------------------------------------------------------
  nodes = [    {
      name        = "k8s-dev-worker-01"
      vmid        = 310
      target_node = "pve-04"
      ip_address  = "10.10.20.21"
      hostname    = "k8s-dev-worker-01"
      fqdn        = "k8s-dev-worker-01.dev.k8s.sinlessgames.com"
      storage     = "vm_disks_04"
    },    {
      name        = "k8s-dev-worker-02"
      vmid        = 311
      target_node = "pve-05"
      ip_address  = "10.10.20.22"
      hostname    = "k8s-dev-worker-02"
      fqdn        = "k8s-dev-worker-02.dev.k8s.sinlessgames.com"
      storage     = "vm_disks_05"
    }  ]

  # --------------------------------------------------------------------------
  # Proxmox configuration
  # --------------------------------------------------------------------------
  clone_template = "debian-13-template"
  storage        = "VM_Disks"

  # --------------------------------------------------------------------------
  # Resource allocation
  # --------------------------------------------------------------------------
  cpu_cores   = 4
  cpu_sockets = 1
  memory_mb   = 8192
  disk_size   = "100G"

  # --------------------------------------------------------------------------
  # Network configuration
  # --------------------------------------------------------------------------
  network_bridge = "vmbr1"
  vlan_id        = 20
  gateway        = "10.10.20.1"
  cidr_subnet    = "/24"
  nameservers    = "10.10.10.1 1.1.1.1"
  search_domain  = "dev.k8s.sinlessgames.com"

  # --------------------------------------------------------------------------
  # Metadata / access
  # --------------------------------------------------------------------------
  tags = [
    "kubernetes",
    "rke2",
    "worker"
  ]

  ssh_keys     = var.kubernetes_ssh_keys
  default_user = "sinless777"
  cicustom_user_snippet_enabled = true

  # --------------------------------------------------------------------------
  # Lifecycle
  # --------------------------------------------------------------------------
  start_at_node_boot = true
  force_create       = true
  startup_order      = 20

  depends_on = [module.kubernetes_dev_master]
}

// ============================================================================
// Outputs
// ============================================================================

output "cluster_status_dev" {
  description = "Kubernetes cluster VM deployment status for dev"
  value = {
    cluster_name  = "k8s-dev"
    environment   = "dev"
    master_count  = 1
    worker_count  = 2
    vlan_id       = 20
    pod_cidr      = "10.42.0.0/16"
    service_cidr  = "10.43.0.0/16"
    cluster_dns   = "10.43.0.10"
    search_domain = "dev.k8s.sinlessgames.com"
    master_ips    = ["10.10.20.11"]
    worker_ips    = ["10.10.20.21", "10.10.20.22"]
  }
}
