apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sample-gpu-workload.yaml
  - sample-mesh-workload.yaml
  - sample-rollout.yaml
  - sample-service-monitor.yaml
  - sample-external-secret.yaml
