apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-ca
  namespace: security
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFNTCCAx2gAwIBAgIUVJGQcLVk4kOH3WHZDqCybF42AZkwDQYJKoZIhvcNAQEL
    BQAwITEfMB0GA1UEAwwWU2lubGVzcyBWYXVsdCBMb2NhbCBDQTAeFw0yNjA0MDQx
    OTMyMjRaFw0zNjA0MDExOTMyMjRaMCExHzAdBgNVBAMMFlNpbmxlc3MgVmF1bHQg
    TG9jYWwgQ0EwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCYUPeRw9E3
    0cGhWcBw1/RlyMIwHklsTwOFPoHmA2nXWf6SllWbSef90aQSzKsdBIXhDhInEAqX
    AtIZhMseiCXZDivQzvZ2V1FsNP1ZZWP6har/coxHhUvO1QJQ2I7VjRgWtKY5xvRp
    0xM38In74f69noyFaPZViuPoDHIS1WT3nuQ6BZehKI6nGANkR8Z8F1KvQ3gZ1rim
    Dv8RimfkqVEzPw6lldeEz9CA82LHcdLGctT559fM+WRF9isEsmioM1eXx8mUFH7d
    7HHMokUSntzzWfe6fSwlXjYiI9minvgUkmdC07xEK3/YDdbyAGQPmyd83UzYPAEI
    xWfopv1uehcraHqZeeUjlMDnoMkuo1l6RY8qXjDTG4uVpNtunzRk0SaZD7tx/ttA
    /k302KWg0wl+iZYMawb85x0Sq5UitKd7qcDe6UQEsP2/WBCPtsQXcKRvrAYv2XP+
    QSle0y80f4MHe0sn7Io4HJ0o/IMMot5ZSjv8rDnghAjOcJ86DWWsUPnbsZN5ogT1
    YbXLlJ1HhEITZwI1wqDv9PQEaDgBIdi5r4va0La1PdJeGA3dxCbVWFa9jxUni0+2
    /aIKWeS8bNN1s/oYslmcDBatZtMqa7kYTVVn3Wrto5+gFLiyfth5YuLDa7htAZ0T
    P8jLOz3YgV9tF4XdOVA5qI/mEwoxAAOKnwIDAQABo2UwYzAhBgNVHREEGjAYghZT
    aW5sZXNzIFZhdWx0IExvY2FsIENBMA4GA1UdDwEB/wQEAwIBBjAPBgNVHRMBAf8E
    BTADAQH/MB0GA1UdDgQWBBRf6pwgO6T5PH7XvCnH4lVlkiBvSzANBgkqhkiG9w0B
    AQsFAAOCAgEALdJRGRG3/BAcfSeXaPRCiMX5WlzMxF6dtd2ky8VMN36B/zK/MtuU
    pH9o000kOjIMtUAjbMJhOkHypBuSI41RSsa13i4KNvaWtOcJyuc0iNG9A9jfQYnZ
    plleZlq1vA7nxBItTEwq2K0tm4rjMjALfKXZzkdrYJygKT5af8+971CLxG85k8Gh
    fObNljIONGNvOP6bQGyptpnLAbHu5kQtztK20AdnoIJqTt1eBYkckbD7WzLbOjls
    goDzkrWDd4eUUO37TP/k09H6Q+ZyDbjRyXJe39JNygydBSslWcrjQESaEza76Hiv
    bDT3CXB2AfRPZ98IM3zhMmqaFTqdRCCwTtzRn0UtNpkX34w06aGr9urWRYiamEdv
    Vd4V4poxWc+hUkeMrXBuSCW0Cr0rNgwE29fP4EaSM8TC0VLGRWvT++czZmqGg02u
    oiWK8EKXMGTPJuImKcOfx7DRYwc6lC7GNp/yTgTHCGfg2ecwJJZiLNhoYbWW/M30
    TwQuD7xidfLIyl8nmP9PBKWg/XWUNtseuByp8dgjF0rbrlgG+yeMTkr1yJO3EWqm
    nrFM0S4wmrfcepSDqgc3rVY+2w0iAxA8R4d5CWU6ObGzITnzGWkW9v7H7oa4CtJv
    xwDpsVkC1oVm1bvX+ibJSklY1zGcs5NIzFkZtl5iaLYZKaoFfBb7Llk=
    -----END CERTIFICATE-----
