# Kubernetes/apps/prod/security/external-secrets/externalsecret-platform-integrations.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: platform-integrations
  namespace: security
  labels:
    app.kubernetes.io/name: platform-integrations
    app.kubernetes.io/component: integration-credentials
    app.kubernetes.io/part-of: external-secrets
    security.sinlessgames.io/secret-source: vault
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend

  target:
    name: platform-integrations
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: platform-integrations
          app.kubernetes.io/component: integration-credentials
          app.kubernetes.io/part-of: external-secrets
          security.sinlessgames.io/managed-by: external-secrets

  data:
    - secretKey: account_id
      remoteRef:
        key: cloudflare/api
        property: account_id