apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-s3-credentials
  namespace: security
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: velero-s3-credentials
    template:
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .AWS_ACCESS_KEY_ID }}
          aws_secret_access_key={{ .AWS_SECRET_ACCESS_KEY }}
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: kubernetes/production/integrations
        property: velero_access_key
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: kubernetes/production/integrations
        property: velero_secret_key
    - secretKey: S3_URL
      remoteRef:
        key: kubernetes/production/integrations
        property: garage_s3_url_internal
