# Kubernetes/apps/prod/security/external-secrets/externalsecret-velero-s3.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: velero-s3-credentials
  namespace: security
  labels:
    app.kubernetes.io/name: velero-s3-credentials
    app.kubernetes.io/component: backup-credentials
    app.kubernetes.io/part-of: velero
    security.sinlessgames.io/secret-source: vault
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend

  target:
    name: velero-s3-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          app.kubernetes.io/name: velero-s3-credentials
          app.kubernetes.io/component: backup-credentials
          app.kubernetes.io/part-of: velero
          security.sinlessgames.io/managed-by: external-secrets
      data:
        cloud: |
          [default]
          aws_access_key_id={{ .awsAccessKeyId }}
          aws_secret_access_key={{ .awsSecretAccessKey }}

        s3_url: "{{ .s3Url }}"

  data:
    - secretKey: awsAccessKeyId
      remoteRef:
        key: kubernetes/production/integrations
        property: velero_access_key

    - secretKey: awsSecretAccessKey
      remoteRef:
        key: kubernetes/production/integrations
        property: velero_secret_key

    - secretKey: s3Url
      remoteRef:
        key: kubernetes/production/integrations
        property: garage_s3_url_internal