apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap-vault-ca.yaml
  - clusterrolebinding-tokenreview.yaml
  - clustersecretstore-vault.yaml
  - externalsecret-platform-integrations.yaml
  - externalsecret-velero-s3.yaml
