---
dns:
  vars:
    ansible_user: "sinless777"
  hosts:
    dns-pi:
      ansible_host: 10.10.10.12
    dns-01:
      ansible_host: 10.10.10.9
    dns-02:
      ansible_host: 10.10.10.11
    dns-03:
      ansible_host: 10.10.10.13
