---
wazuh:
  vars:
    ansible_user: "sinless777"
    ansible_ssh_private_key_file: "/home/sinless777/Projects/Infrastructure/.outputs/ssh/sinless777/id_ed25519"
    ansible_python_interpreter: "/usr/bin/python3"
    ansible_remote_tmp: "/tmp/.ansible/tmp"
    ansible_ssh_common_args: >-
      -o StrictHostKeyChecking=no
      -o UserKnownHostsFile=/dev/null
      -o PreferredAuthentications=publickey
      -o PubkeyAuthentication=yes
      -o PasswordAuthentication=no
      -o IdentitiesOnly=yes
      -o IdentityAgent=none
      -o CertificateFile=/home/sinless777/Projects/Infrastructure/.outputs/ssh/sinless777/id_ed25519-cert.pub
  hosts:
    wazuh-01:
      ansible_host: "10.10.10.21"
