apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-probes
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: check-probes
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - networking
                - monitoring
          - resources:
              kinds:
                - Pod
              names:
                - n8n*
              namespaces:
                - sinless-games
      validate:
        message: Liveness and readiness probes are required for all containers.
        foreach:
          - list: "request.object.spec.containers"
            deny:
              conditions:
                any:
                  - key: "{{ element.livenessProbe }}"
                    operator: Equals
                    value: null
                  - key: "{{ element.readinessProbe }}"
                    operator: Equals
                    value: null
