apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: cloudflared-probes
  namespace: networking
spec:
  exceptions:
    - policyName: require-probes
      ruleNames:
        - check-probes
        - autogen-check-probes
  match:
    any:
      - resources:
          kinds:
            - Pod
            - DaemonSet
          namespaces:
            - networking
          selector:
            matchLabels:
              app.kubernetes.io/name: cloudflared
