---
# =============================================================================
# Kubernetes Production Cluster Variables - Control Plane
# =============================================================================

kubernetes_control_plane_group_name: "kubernetes_prod_control_plane"
kubernetes_control_plane_first_host: "rke2-prod-cp-01"
kubernetes_control_plane_first_ip: "10.10.40.11"

kubernetes_rke2_cluster_group_name: "kubernetes_prod"
kubernetes_rke2_servers_group_name: "kubernetes_prod_control_plane"
kubernetes_rke2_agents_group_name: "kubernetes_prod_workers"

kubernetes_rke2_server_node_labels:
  - "sinlessgames.com/role=control-plane"
  - "sinlessgames.com/environment=prod"
  - "sinlessgames.com/region=homelab-prod"
kubernetes_rke2_server_tls_sans:
  - "{{ kubernetes_api_vip }}"
  - "{{ kubernetes_api_fqdn }}"
