---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart etcd
  ansible.builtin.systemd:
    name: etcd
    state: restarted

- name: Restart patroni
  ansible.builtin.systemd:
    name: patroni
    state: restarted

- name: Restart pgbouncer
  ansible.builtin.systemd:
    name: pgbouncer
    state: restarted

- name: Restart haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: restarted

- name: Restart keepalived
  ansible.builtin.systemd:
    name: keepalived
    state: restarted

- name: Restart pganalyze collector
  ansible.builtin.systemd:
    name: "{{ postgres_pganalyze_service_name }}"
    state: restarted

- name: Restart pgadmin
  ansible.builtin.systemd:
    name: "{{ postgres_pgadmin_service_name }}"
    state: restarted
