---
# =============================================================================
# Kubernetes Staging Cluster Variables - Worker Nodes
# =============================================================================

kubernetes_rke2_cluster_group_name: "kubernetes_staging"
kubernetes_rke2_servers_group_name: "kubernetes_staging_control_plane"
kubernetes_rke2_agents_group_name: "kubernetes_staging_workers"
kubernetes_rke2_agent_node_labels:
  - "node-role.kubernetes.io/worker=true"
  - "topology.kubernetes.io/environment=staging"
