apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: shared-edge
  namespace: istio-system
spec:
  selector:
    istio: ingress
  servers:
    - port:
        name: http
        number: 80
        protocol: HTTP
      hosts:
        - "*.sinlessgames.com"
        - "*.helixaibot.com"
    - port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: wildcard-sinlessgames-com
      hosts:
        - "*.sinlessgames.com"
        - "*.helixaibot.com"
