apiVersion: v1
kind: Service
metadata:
  name: cloudflared-origin-compat
  namespace: istio-system
spec:
  type: ClusterIP
  clusterIP: 10.43.106.248
  selector:
    app: istio-ingress
    istio: ingress
  ports:
    - name: status-port
      port: 15021
      targetPort: 15021
      protocol: TCP
    - name: http2
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP
