---
- name: Run Postgres deploy phase
  ansible.builtin.include_vars:
    file: "{{ role_path }}/defaults/deploy.yaml"
    name: __postgres_deploy_defaults
  when: "'deploy' in postgres_role_phases"
  tags:
    - postgres
    - deploy

- name: Apply Postgres deploy defaults
  ansible.builtin.set_fact:
    "{{ item.key }}": "{{ item.value }}"
  loop: "{{ (__postgres_deploy_defaults | default({})) | dict2items }}"
  when: "'deploy' in postgres_role_phases"
  tags:
    - postgres
    - deploy

- name: Include Postgres deploy tasks
  ansible.builtin.include_tasks: deploy.yaml
  when: "'deploy' in postgres_role_phases"
  tags:
    - postgres
    - deploy

- name: Run Postgres configure phase
  ansible.builtin.include_tasks: configure-main.yaml
  when: "'configure' in postgres_role_phases"
  tags:
    - postgres
    - configure
