---
# =============================================================================
# packages — defaults
# -----------------------------------------------------------------------------
# Control which package groups are installed
# =============================================================================

packages_enabled_groups:
  - base
  - cli
  - dev
  - net
  - system
