# Kubernetes/apps/prod/kube-system/config/externalsecret-longhorn.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-backup-credentials
  namespace: kube-system
  labels:
    app.kubernetes.io/name: longhorn-backup-credentials
    app.kubernetes.io/component: backup-credentials
    app.kubernetes.io/part-of: longhorn
    security.sinlessgames.io/secret-source: vault
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend

  target:
    name: longhorn-backup-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: longhorn-backup-credentials
          app.kubernetes.io/component: backup-credentials
          app.kubernetes.io/part-of: longhorn
          security.sinlessgames.io/managed-by: external-secrets

  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: kubernetes/production/integrations
        property: longhorn_backup_access_key

    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: kubernetes/production/integrations
        property: longhorn_backup_secret_key

    - secretKey: AWS_ENDPOINTS
      remoteRef:
        key: kubernetes/production/integrations
        property: garage_s3_url_internal

    - secretKey: AWS_REGION
      remoteRef:
        key: kubernetes/production/integrations
        property: garage_s3_region