apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-backup-credentials
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: longhorn-backup-credentials
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: kubernetes/production/integrations
        property: longhorn_backup_access_key
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: kubernetes/production/integrations
        property: longhorn_backup_secret_key
