# Kubernetes/apps/prod/monitoring/opentelemetry-operator/values.yaml

admissionWebhooks:
  create: true
  failurePolicy: Fail
  certManager:
    enabled: true

manager:
  collectorImage:
    repository: otel/opentelemetry-collector-k8s

  serviceMonitor:
    enabled: false

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  securityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
