storage:
  trace:
    backend: s3
    s3:
      bucket: k8s-prod-tempo
      endpoint: ${S3_ENDPOINT}
      access_key: ${S3_ACCESS_KEY_ID}
      secret_key: ${S3_SECRET_ACCESS_KEY}
      insecure: false
traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
metricsGenerator:
  enabled: true
  remoteWriteUrl: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/api/v1/write
