# Kubernetes/apps/prod/monitoring/tempo/values.yaml

storage:
  trace:
    backend: s3
    s3:
      bucket: k8s-prod-tempo
      endpoint: ${S3_ENDPOINT}
      region: ${S3_REGION}
      access_key: ${S3_ACCESS_KEY_ID}
      secret_key: ${S3_SECRET_ACCESS_KEY}
      insecure: true
      forcepathstyle: true

traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true

overrides:
  defaults:
    metrics_generator:
      processors:
        - service-graphs
        - span-metrics
        - local-blocks

metricsGenerator:
  enabled: true
  remoteWriteUrl: http://mimir-nginx.monitoring.svc.cluster.local/api/v1/push
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  extraEnvFrom:
    - secretRef:
        name: tempo-s3-credentials
  extraArgs:
    - -config.expand-env=true

compactor:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  extraEnvFrom:
    - secretRef:
        name: tempo-s3-credentials
  extraArgs:
    - -config.expand-env=true

distributor:
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  extraEnvFrom:
    - secretRef:
        name: tempo-s3-credentials
  extraArgs:
    - -config.expand-env=true

ingester:
  replicas: 3
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
  extraEnvFrom:
    - secretRef:
        name: tempo-s3-credentials
  extraArgs:
    - -config.expand-env=true

querier:
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  extraEnvFrom:
    - secretRef:
        name: tempo-s3-credentials
  extraArgs:
    - -config.expand-env=true

queryFrontend:
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  extraEnvFrom:
    - secretRef:
        name: tempo-s3-credentials
  extraArgs:
    - -config.expand-env=true

serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack