# Kubernetes/apps/prod/sinless-games/garage/externalsecret-garage.yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: garage-secrets
  namespace: sinless-games
  labels:
    app.kubernetes.io/name: garage-secrets
    app.kubernetes.io/component: object-storage-credentials
    app.kubernetes.io/part-of: garage
    security.sinlessgames.io/secret-source: vault
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend

  target:
    name: garage-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: garage-secrets
          app.kubernetes.io/component: object-storage-credentials
          app.kubernetes.io/part-of: garage
          security.sinlessgames.io/managed-by: external-secrets

  data:
    - secretKey: garage_rpc_secret
      remoteRef:
        key: kubernetes/production/integrations
        property: garage_rpc_secret

    - secretKey: garage_admin_token
      remoteRef:
        key: kubernetes/production/integrations
        property: garage_admin_token

    - secretKey: garage_metrics_token
      remoteRef:
        key: kubernetes/production/integrations
        property: garage_metrics_token

    - secretKey: garage_admin_user
      remoteRef:
        key: kubernetes/production/integrations
        property: garage_admin_user

    - secretKey: garage_ui_auth_bcrypt
      remoteRef:
        key: kubernetes/production/integrations
        property: garage_ui_auth_bcrypt

    - secretKey: s3_access_key_id
      remoteRef:
        key: kubernetes/production/integrations
        property: s3_access_key_id

    - secretKey: s3_secret_access_key
      remoteRef:
        key: kubernetes/production/integrations
        property: s3_secret_access_key