apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: garage-secrets
  namespace: sinless-games
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: garage-secrets
    creationPolicy: Owner
  data:
    - secretKey: garage_rpc_secret
      remoteRef:
        key: kubernetes/production/integrations
        property: garage_rpc_secret
    - secretKey: garage_admin_token
      remoteRef:
        key: kubernetes/production/integrations
        property: garage_admin_token
    - secretKey: garage_metrics_token
      remoteRef:
        key: kubernetes/production/integrations
        property: garage_metrics_token
    - secretKey: s3_access_key_id
      remoteRef:
        key: kubernetes/production/integrations
        property: s3_access_key_id
    - secretKey: s3_secret_access_key
      remoteRef:
        key: kubernetes/production/integrations
        property: s3_secret_access_key
    - secretKey: garage_ui_auth_bcrypt
      remoteRef:
        key: kubernetes/production/integrations
        property: garage_ui_auth_bcrypt
    - secretKey: garage_admin_user
      remoteRef:
        key: kubernetes/production/integrations
        property: garage_admin_user
    - secretKey: loki_bucket
      remoteRef:
        key: kubernetes/production/cluster
        property: loki_bucket
    - secretKey: loki_s3_access_key_id
      remoteRef:
        key: kubernetes/production/integrations
        property: loki_s3_access_key_id
    - secretKey: loki_s3_secret_access_key
      remoteRef:
        key: kubernetes/production/integrations
        property: loki_s3_secret_access_key
    - secretKey: mimir_bucket
      remoteRef:
        key: kubernetes/production/cluster
        property: mimir_bucket
    - secretKey: mimir_s3_access_key_id
      remoteRef:
        key: kubernetes/production/integrations
        property: mimir_s3_access_key_id
    - secretKey: mimir_s3_secret_access_key
      remoteRef:
        key: kubernetes/production/integrations
        property: mimir_s3_secret_access_key
    - secretKey: tempo_bucket
      remoteRef:
        key: kubernetes/production/cluster
        property: tempo_bucket
    - secretKey: tempo_s3_access_key_id
      remoteRef:
        key: kubernetes/production/integrations
        property: tempo_s3_access_key_id
    - secretKey: tempo_s3_secret_access_key
      remoteRef:
        key: kubernetes/production/integrations
        property: tempo_s3_secret_access_key
    - secretKey: pyroscope_bucket
      remoteRef:
        key: kubernetes/production/cluster
        property: pyroscope_bucket
    - secretKey: pyroscope_s3_access_key_id
      remoteRef:
        key: kubernetes/production/integrations
        property: pyroscope_s3_access_key_id
    - secretKey: pyroscope_s3_secret_access_key
      remoteRef:
        key: kubernetes/production/integrations
        property: pyroscope_s3_secret_access_key
    - secretKey: longhorn_backup_bucket
      remoteRef:
        key: kubernetes/production/cluster
        property: longhorn_backup_bucket
    - secretKey: longhorn_backup_access_key
      remoteRef:
        key: kubernetes/production/integrations
        property: longhorn_backup_access_key
    - secretKey: longhorn_backup_secret_key
      remoteRef:
        key: kubernetes/production/integrations
        property: longhorn_backup_secret_key
    - secretKey: velero_bucket
      remoteRef:
        key: kubernetes/production/cluster
        property: velero_bucket
    - secretKey: velero_access_key
      remoteRef:
        key: kubernetes/production/integrations
        property: velero_access_key
    - secretKey: velero_secret_key
      remoteRef:
        key: kubernetes/production/integrations
        property: velero_secret_key
