apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: garage-secrets
  namespace: sinless-games
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: garage-secrets
    creationPolicy: Owner
  data:
    - secretKey: garage_rpc_secret
      remoteRef:
        key: kubernetes/production/integrations
        property: garage_rpc_secret
    - secretKey: garage_admin_token
      remoteRef:
        key: kubernetes/production/integrations
        property: garage_admin_token
    - secretKey: garage_metrics_token
      remoteRef:
        key: kubernetes/production/integrations
        property: garage_metrics_token
    - secretKey: s3_access_key_id
      remoteRef:
        key: kubernetes/production/integrations
        property: s3_access_key_id
    - secretKey: s3_secret_access_key
      remoteRef:
        key: kubernetes/production/integrations
        property: s3_secret_access_key
