apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storageclass-garage.yaml
  - externalsecret-garage.yaml
  - service-headless.yaml
  - service-s3.yaml
  - service-admin.yaml
  - service-ui.yaml
  - networkpolicy-garage.yaml
  - networkpolicy-garage-ui.yaml
  - statefulset-garage.yaml
  - deployment-garage-webui.yaml
  - ingress-garage-ui.yaml
  - virtualservice-garage.yaml
