apiVersion: v1
kind: Service
metadata:
  name: garage-headless
  namespace: sinless-games
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: garage
  ports:
    - name: tcp-rpc
      port: 3901
      targetPort: 3901
