apiVersion: v1
kind: ServiceAccount
metadata:
  name: garage-webui
  namespace: sinless-games
  labels:
    app.kubernetes.io/name: garage-webui
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: garage
automountServiceAccountToken: false
