apiVersion: v1
kind: Service
metadata:
  name: garage-ui
  namespace: sinless-games
spec:
  selector:
    app.kubernetes.io/name: garage-webui
  ports:
    - name: http
      port: 3909
      targetPort: 3909
