autoscaleMin: 3
autoscaleMax: 5
replicaCount: 3
global:
  proxy:
    autoInject: enabled
meshConfig:
  accessLogFile: /dev/stdout
  enablePrometheusMerge: true
pilot:
  autoscaleEnabled: true
  env:
    EXTERNAL_ISTIOD: "false"
