apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: helix-ai-workload-secrets
  namespace: helix-ai
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: helix-ai-workload-secrets
  data:
    - secretKey: redis_password
      remoteRef:
        key: kubernetes/production/workloads
        property: redis_password
