apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: helix-ai
spec:
  limits:
    - type: Container
      min:
        cpu: 50m
        memory: 64Mi
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: "1"
        memory: 1Gi
      max:
        cpu: "4"
        memory: 16Gi
      maxLimitRequestRatio:
        cpu: "10"
        memory: "8"