configs:
  params:
    server.insecure: true
  secret:
    argocdServerAdminPassword: '$2b$10$vJGbHySXxfGK96qjNX5aeO8GcoQm3Db.RAJs7yF3QgqoLqG4FuCMK'
server:
  ingress:
    enabled: false
controller:
  replicas: 1
repoServer:
  replicas: 2
applicationSet:
  replicas: 2
redis:
  enabled: true
redisSecretInit:
  enabled: false
