---
- name: Run Technitium deploy phase
  ansible.builtin.include_vars:
    file: "{{ role_path }}/defaults/deploy.yaml"
    name: __technitium_deploy_defaults
  when: "'deploy' in technitium_role_phases"
  tags:
    - technitium
    - deploy

- name: Apply Technitium deploy defaults
  ansible.builtin.set_fact:
    "{{ item.key }}": "{{ item.value }}"
  loop: "{{ (__technitium_deploy_defaults | default({})) | dict2items }}"
  when: "'deploy' in technitium_role_phases"
  tags:
    - technitium
    - deploy

- name: Include Technitium deploy tasks
  ansible.builtin.include_tasks: deploy.yaml
  when: "'deploy' in technitium_role_phases"
  tags:
    - technitium
    - deploy

- name: Run Technitium configure phase
  ansible.builtin.include_tasks: configure-main.yaml
  when: "'configure' in technitium_role_phases"
  tags:
    - technitium
    - configure
