proxmox_node:

  licensed: false

  enable_iommu: true
  enable_hugepages: false
  hugepages_count: 0

  enable_ceph_prereqs: true

  enable_api_users: true

  timezone: "UTC"

ssh_output_root: "{{ ssh_repo_root }}/.outputs"
ssh_output_base: "{{ ssh_output_root }}/ssh"
ssh_ca_output_dir: "{{ ssh_output_root }}/ssh-ca"

# Absolute path to repo root (git-based, execution-safe)
ssh_repo_root: "{{ lookup('ansible.builtin.pipe', 'git rev-parse --show-toplevel') | trim }}"