apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: argocd-ui
  namespace: gitops
spec:
  host: argo-cd-argocd-server.gitops.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL