apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: argocd-ui
  namespace: gitops
spec:
  exportTo:
    - istio-system
  gateways:
    - istio-system/shared-edge
  hosts:
    - argocd.sinlessgames.com
  http:
    - name: argocd-ui
      match:
        - uri:
            prefix: /
      route:
        - destination:
            host: argo-cd-argocd-server.gitops.svc.cluster.local
            port:
              number: 80