---
# =============================================================================
# SSH Role Variables
# =============================================================================

ssh_supported_key_types:
  - ed25519
  - rsa
