# Kubernetes/apps/prod/security/namespace/limitrange.yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: security
  labels:
    app.kubernetes.io/name: security-default-limits
    app.kubernetes.io/component: namespace-policy
    app.kubernetes.io/part-of: security
    security.sinlessgames.io/policy: resource-limits
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      default:
        cpu: 500m
        memory: 512Mi
      min:
        cpu: 10m
        memory: 32Mi
      max:
        cpu: "4"
        memory: 4Gi