apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: sinless-games
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/part-of: sinless-games-platform
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Platform
    gethomepage.dev/name: Homepage
    gethomepage.dev/icon: homepage.png
    gethomepage.dev/description: Platform dashboard
    gethomepage.dev/href: https://homepage.sinlessgames.com
spec:
  selector:
    app.kubernetes.io/name: homepage
  ports:
    - name: http
      port: 3000
      targetPort: http
