apiVersion: v1
kind: ResourceQuota
metadata:
  name: kube-system-quota
  namespace: kube-system
spec:
  hard:
    requests.cpu: "64"
    requests.memory: 160Gi
    persistentvolumeclaims: "100"
    pods: "600"
