apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sinless-games-workload-secrets
  namespace: sinless-games
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: sinless-games-workload-secrets
  data:
    - secretKey: n8n_basic_auth_password
      remoteRef:
        key: kubernetes/production/integrations
        property: n8n_basic_auth_password
