apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret-sinless-games-workloads.yaml
  - resourcequota.yaml
  - limitrange.yaml
  - networkpolicy-default-deny.yaml
  - authorizationpolicy-default.yaml
  - peerauthentication-default.yaml
  - n8n-deployment.yaml
