apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret-sinless-games-workloads.yaml
  - networkpolicy-default-deny.yaml
  - networkpolicy-allow-egress.yaml
  - networkpolicy-mailu.yaml
  - networkpolicy-n8n.yaml
  - authorizationpolicy-default.yaml
  - peerauthentication-default.yaml
  - authorizationpolicy-opencost-monitoring.yaml
  - authorizationpolicy-require-mtls.yaml
