apiVersion: v1
kind: ResourceQuota
metadata:
  name: sinless-games-quota
  namespace: sinless-games
spec:
  hard:
    requests.cpu: "16"
    requests.memory: 32Gi
    limits.cpu: "32"
    limits.memory: 64Gi
    persistentvolumeclaims: "20"
