# Kubernetes/apps/prod/monitoring/namespace/limitrange.yaml
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: monitoring
  labels:
    app.kubernetes.io/name: monitoring-default-limits
    app.kubernetes.io/component: namespace-policy
    app.kubernetes.io/part-of: monitoring
    security.sinlessgames.io/policy: resource-limits
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 128Mi
      default:
        cpu: 500m
        memory: 768Mi
      min:
        cpu: 10m
        memory: 32Mi
      max:
        cpu: "4"
        memory: 8Gi