apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: monitoring
spec:
  hard:
    requests.cpu: "32"
    requests.memory: 96Gi
    limits.cpu: "96"
    limits.memory: 160Gi
    persistentvolumeclaims: "80"
    pods: "300"
