apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: sinless-games-default
  namespace: sinless-games
spec:
  host: "*.sinless-games.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
