apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: n8n
  namespace: sinless-games
spec:
  gateways:
    - istio-system/shared-edge
  hosts:
    - n8n.helixaibot.com
    - external.helixaibot.com
    - internal.helixaibot.com
  http:
    - route:
        - destination:
            host: n8n.sinless-games.svc.cluster.local
            port:
              number: 80
