---
vault_prod:
  hosts:
  vars:
    vault_version: "1.21.3"
    vault_port: 8200
    vault_cluster_port: 8201
    vault_storage_path: "/opt/vault/data"
    vault_log_path: "/opt/vault/logs"
    vault_tls_enabled: true
    vault_environment: "prod"
