---
- name: reload haproxy
  systemd:
    name: "{{ haproxy_service_name }}"
    state: reloaded
  become: yes

- name: restart keepalived
  systemd:
    name: "{{ keepalived_service_name }}"
    state: restarted
  become: yes

- name: restart haproxy
  systemd:
    name: "{{ haproxy_service_name }}"
    state: restarted
  become: yes
