apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: actions-runner-controller
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "14"
spec:
  project: platform
  sources:
    - repoURL: https://actions-runner-controller.github.io/actions-runner-controller
      chart: actions-runner-controller
      targetRevision: 0.23.7
      helm:
        values: |
          authSecret:
            enabled: true
            create: false
            name: controller-manager
          controllerManager:
            metrics:
              serviceMonitor:
                enable: true
          githubWebhookServer:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
