apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sinless-games-docs
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "18"
    platform.sinlessgames.io/depends-on: "sinless-games-mesh,networking-config"
spec:
  project: platform
  source:
    repoURL: https://github.com/SinLess-Games/Infrastructure.git
    targetRevision: main
    path: Kubernetes/apps/prod/sinless-games/docs
  destination:
    server: https://kubernetes.default.svc
    namespace: sinless-games
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
