apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: networking-config
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: platform
  source:
    repoURL: https://github.com/Sinless777/Infrastructure.git
    targetRevision: main
    path: Kubernetes/apps/prod/networking/config
  destination:
    server: https://kubernetes.default.svc
    namespace: networking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
