apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces-gitops
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  project: platform
  source:
    repoURL: https://github.com/Sinless777/Infrastructure.git
    targetRevision: main
    path: Kubernetes/apps/prod/gitops/namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
