apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-gpu-operator
  namespace: gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
spec:
  project: platform
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  sources:
    - repoURL: https://helm.ngc.nvidia.com/nvidia
      chart: gpu-operator
      targetRevision: 24.9.2
      helm:
        valueFiles:
          - $values/Kubernetes/apps/prod/kube-system/nvidia-gpu-operator/values.yaml
    - repoURL: https://github.com/SinLess-Games/Infrastructure.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true